### ISSUE TITLE
[GENERAL] Possibile problema con la versione di spid-saml-check

### ISSUE THREAD

**Issue by paolopoliti** [INPS-it/bugs.inps.it#26]
Quando lancio il comando docker compose ottengo questo output:

```
bugsinpsit-spid-saml-check-1  | > spid-validator@1.0.0 start-prod /spid-saml-check/spid-validator
bugsinpsit-spid-saml-check-1  | > node server/spid-validator.js
bugsinpsit-spid-saml-check-1  | 
bugsinpsit-spid-saml-check-1  | internal/modules/cjs/loader.js:818
bugsinpsit-spid-saml-check-1  |   throw err;
bugsinpsit-spid-saml-check-1  |   ^
bugsinpsit-spid-saml-check-1  | 
bugsinpsit-spid-saml-check-1  | Error: Cannot find module 'express'
bugsinpsit-spid-saml-check-1  | Require stack:
bugsinpsit-spid-saml-check-1  | - /spid-saml-check/spid-validator/server/spid-validator.js
bugsinpsit-spid-saml-check-1  |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
bugsinpsit-spid-saml-check-1  |     at Function.Module._load (internal/modules/cjs/loader.js:667:27)
bugsinpsit-spid-saml-check-1  |     at Module.require (internal/modules/cjs/loader.js:887:19)
bugsinpsit-spid-saml-check-1  |     at require (internal/modules/cjs/helpers.js:74:18)
bugsinpsit-spid-saml-check-1  |     at Object.<anonymous> (/spid-saml-check/spid-validator/server/spid-validator.js:2:17)
bugsinpsit-spid-saml-check-1  |     at Module._compile (internal/modules/cjs/loader.js:999:30)
bugsinpsit-spid-saml-check-1  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
bugsinpsit-spid-saml-check-1  |     at Module.load (internal/modules/cjs/loader.js:863:32)
bugsinpsit-spid-saml-check-1  |     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
bugsinpsit-spid-saml-check-1  |     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12) {
bugsinpsit-spid-saml-check-1  |   code: 'MODULE_NOT_FOUND',
bugsinpsit-spid-saml-check-1  |   requireStack: [ '/spid-saml-check/spid-validator/server/spid-validator.js' ]
bugsinpsit-spid-saml-check-1  | }
bugsinpsit-spid-saml-check-1  | npm ERR! code ELIFECYCLE
bugsinpsit-spid-saml-check-1  | npm ERR! errno 1
bugsinpsit-spid-saml-check-1  | npm ERR! spid-validator@1.0.0 start-prod: `node server/spid-validator.js`
bugsinpsit-spid-saml-check-1  | npm ERR! Exit status 1
bugsinpsit-spid-saml-check-1  | npm ERR! 
bugsinpsit-spid-saml-check-1  | npm ERR! Failed at the spid-validator@1.0.0 start-prod script.
bugsinpsit-spid-saml-check-1  | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
bugsinpsit-spid-saml-check-1  | npm WARN Local package.json exists, but node_modules missing, did you mean to install?
bugsinpsit-spid-saml-check-1  | 
bugsinpsit-spid-saml-check-1  | npm ERR! A complete log of this run can be found in:
bugsinpsit-spid-saml-check-1  | npm ERR!     /root/.npm/_logs/2022-06-21T13_34_35_593Z-debug.log
```

Lo stesso problema non si presenta se invece uso la versione v.1.8.1 di spid-saml-check.

**Comment by peppelinux** [comment]
Ciao @paolopoliti 
questa issue è relativa a https://github.com/italia/spid-saml-check
