### ISSUE TITLE
[GENERAL] Possibile problema con la versione di djangosaml2

### ISSUE THREAD

**Issue by paolopoliti** [INPS-it/bugs.inps.it#28]
Quando faccio il dev setup ottengo questo output dal docker service 'taiga back'.

```
bugsinpsit-taiga-back-1       |   Traceback (most recent call last):
bugsinpsit-taiga-back-1       |   File "/taiga-back/manage.py", line 17, in <module>
bugsinpsit-taiga-back-1       |     execute_from_command_line(sys.argv)
bugsinpsit-taiga-back-1       |   File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
bugsinpsit-taiga-back-1       |     utility.execute()
bugsinpsit-taiga-back-1       |   File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 357, in execute
bugsinpsit-taiga-back-1       |     django.setup()
bugsinpsit-taiga-back-1       |   File "/usr/local/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
bugsinpsit-taiga-back-1       |     apps.populate(settings.INSTALLED_APPS)
bugsinpsit-taiga-back-1       |   File "/usr/local/lib/python3.9/site-packages/django/apps/registry.py", line 122, in populate
bugsinpsit-taiga-back-1       |     app_config.ready()
bugsinpsit-taiga-back-1       |   File "/taiga-contrib-inps/back/taiga_contrib_inps/apps.py", line 185, in ready
bugsinpsit-taiga-back-1       |     import djangosaml2_spid.urls
bugsinpsit-taiga-back-1       |   File "/usr/local/lib/python3.9/site-packages/djangosaml2_spid/urls.py", line 4, in <module>
bugsinpsit-taiga-back-1       |     from . import views
bugsinpsit-taiga-back-1       |   File "/usr/local/lib/python3.9/site-packages/djangosaml2_spid/views.py", line 14, in <module>
bugsinpsit-taiga-back-1       |     from djangosaml2.utils import (
bugsinpsit-taiga-back-1       |   File "/usr/local/lib/python3.9/site-packages/djangosaml2/utils.py", line 25, in <module>
bugsinpsit-taiga-back-1       |     from django.utils.http import url_has_allowed_host_and_scheme
bugsinpsit-taiga-back-1       | ImportError: cannot import name 'url_has_allowed_host_and_scheme' from 'django.utils.http' (/usr/local/lib/python3.9/site-packages/django/utils/http.py)
```
Lo stesso problema non si verifica se uso una versione di djangosaml2 inferiore alla v1.5.0.

**Comment by peppelinux** [comment]
purtroppo taiga usa una versione deprecata di django, pertanto nel tuo requirement.txt fixa la versione di djangosaml2 <1.5.0
